config/routes.rb
Rails.application.routes.draw do
  resources :authors do
    collection do
      get 'search'
      get 'handle_search'
    end
  end
  resources :books do
    resources :copies
    resources :reservations
    collection do
      get 'search'
      get 'handle_search'
    end
  end

  resources :authors_books
  resources :borrows

  resources :users
  resources :user_sessions, only: [:create, :destroy]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resources :admins
  resources :admin_sessions, only: [:create, :destroy]
  delete '/admin_sign_out', to: 'admin_sessions#destroy', as: :admin_sign_out
  get '/admin_sign_in', to: 'admin_sessions#new', as: :admin_sign_in

  root 'welcome#index'
end

app/models/ability.rb
# Used by CanCanCan to initialize user rights.
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role == 'sysadmin'
      can :manage, :all
      cannot :create, Reservation
    elsif user.role == 'admin'
      can :manage, :all
      cannot [:create, :update, :destroy], Admin
      cannot :create, Reservation
    elsif user.role == 'user'
      can :read, [Book, Author, Copy]
      can :read, User, id: user.id
      can :read, Borrow, user_id: user.id
      can :create, Reservation
      can :manage, Reservation, user_id: user.id
    else # guest
      can :read, [Book, Author, Copy]
      can :create, User
    end
  end
end

app/models/admin.rb
# Admins used with Authlogic.
# Specifies encryption protocol.
# role used for authorizating access by CanCanCan.
class Admin < ApplicationRecord
  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end

  def role
    if !current_user.nil?
      'user'
    elsif !current_admin.nil?
      if current_admin.login == 'admin'
        'sysadmin'
      else
        'admin'
      end
    else
      'guest'
    end
  end
end

app/models/admin_session.rb
# Authlogic module for storing sessions.
class AdminSession < Authlogic::Session::Base
end

app/models/application_record.rb
# current_% methods used for authentification by Authlogic
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def current_admin_session
    return @current_admin_session if defined?(@current_admin_session)
    @current_admin_session = AdminSession.find
  end

  def current_admin
    return @current_admin if defined?(@current_admin)
    @current_admin = current_admin_session && current_admin_session.admin
  end
end

app/models/author.rb
# Author model
class Author < ApplicationRecord
  has_and_belongs_to_many :books
  validates :name, presence: true
  validates :goodreads_id, presence: true
end

app/models/authors_book.rb
# AuthorsBook model
class AuthorsBook < ApplicationRecord
  validates :author_id, presence: true
  validates :book_id, presence: true
end

app/models/book.rb
# Book model
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  has_many :copies, dependent: :destroy
  has_many :reservations, dependent: :destroy
  validates :title, presence: true
  validates :isbn, presence: true
  validates :goodreads_id, presence: true
end

app/models/borrow.rb
# Borrow model
class Borrow < ApplicationRecord
  belongs_to :user
  belongs_to :copy
  validates :user_id, presence: true
  validates :copy_id, presence: true
  validates :due_date, presence: true
end

app/models/copy.rb
# Copy model
class Copy < ApplicationRecord
  belongs_to :book
  has_one :borrow, dependent: :destroy
  validates :status, presence: true
  validates :book_id, presence: true
end

app/models/reservation.rb
# Reservation model
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :user_id, presence: true
  validates :book_id, presence: true
end

app/models/user.rb
# Users used with Authlogic.
# Specifies encryption protocol.
# role used for authorizating access by CanCanCan.
class User < ApplicationRecord
  has_many :reservations
  has_many :borrows

  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end

  def role
    if !current_user.nil?
      'user'
    elsif !current_admin.nil?
      if current_admin.login == 'admin'
        'sysadmin'
      else
        'admin'
      end
    else
      'guest'
    end
  end
end

app/models/user_session.rb
# Authlogic module for storing sessions.
class UserSession < Authlogic::Session::Base
end

app/helpers/admins_helper.rb
# Empty helper so far.
module AdminsHelper
end

app/helpers/application_helper.rb
# Empty helper so far.
module ApplicationHelper
end

app/helpers/authors_helper.rb
# Empty helper so far.
module AuthorsHelper
end

app/helpers/books_helper.rb
# Empty helper so far.
module BooksHelper
end

app/helpers/borrows_helper.rb
# Empty helper so far.
module BorrowsHelper
end

app/helpers/copies_helper.rb
# Empty helper so far.
module CopiesHelper
end

app/helpers/users_helper.rb
# Empty helper so far.
module UsersHelper
end

app/helpers/welcome_helper.rb
# Empty helper so far.
module WelcomeHelper
end

app/views/admins/index.html.erb
<h1>Listing admins</h1>

<% if can? :create, Admin %>
  <%= link_to 'Create Admin', new_admin_path %>
  <br><br> 
<% end%> 

<table class="table">
  <tr>
    <th>ID</th>
    <th>Login</th>
  </tr>
 
  <% @admins.each do |admin| %>
    <tr>
      <td><%= admin.id %></td>
      <td><%= admin.login %></td>
      <td><%= link_to 'Show', admin_path(admin) %></td>
      <% if can? :destroy, Admin and admin.login != 'admin'%>
        <td><%= link_to 'Delete', admin_path(admin),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      <% end%>
    </tr>
  <% end %>
</table>

<%= link_to 'Home', root_path %>

app/views/admins/new.html.erb
<div class="page-header">
  <h1>Register Admin</h1>
</div>

<%= form_for @admin do |f| %>
  <% if @admin.errors.any? %>
    <div class="panel panel-warning errors">
      <div class="panel-heading">
        <h2>
          <i class="glyphicon glyphicon-exclamation-sign"></i> <%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:
        </h2>
      </div>
      <ul class="panel-body">
        <% @admin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :login %>
    <%= f.text_field :login, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>
<% end %>

<br>
<%= link_to 'Back to Admins', admins_path %>

app/views/admins/show.html.erb
<p>
  <strong>Login:</strong>
  <%= @admin.login %> 
</p>

<%= link_to 'Back to Admins', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibrarySystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Home', root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav pull-right">
            <% if current_user != nil %>
              <li><%= link_to current_user.login, user_path(current_user) %></li>
              <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
            <% elsif current_admin != nil %>
              <li><%= link_to current_admin.login, admins_path %></li>
              <li><%= link_to 'Sign out', admin_sign_out_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign in', sign_in_path %></li>
              <li><%= link_to 'Admin Sign in', admin_sign_in_path %></li>    
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
     
      <%= yield %>
    </div> 
  </body>
</html>