config/routes.rb
Rails.application.routes.draw do
  resources :authors do
    collection do
      get 'search'
      get 'handle_search'
    end
  end
  resources :books do
    resources :copies
    resources :reservations
    collection do
      get 'search'
      get 'handle_search'
    end
  end

  resources :authors_books
  resources :borrows

  resources :users
  resources :user_sessions, only: [:create, :destroy]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resources :admins
  resources :admin_sessions, only: [:create, :destroy]
  delete '/admin_sign_out', to: 'admin_sessions#destroy', as: :admin_sign_out
  get '/admin_sign_in', to: 'admin_sessions#new', as: :admin_sign_in

  root 'welcome#index'
end

app/models/ability.rb
# Used by CanCanCan to initialize user rights.
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role == 'sysadmin'
      can :manage, :all
      cannot :create, Reservation
    elsif user.role == 'admin'
      can :manage, :all
      cannot [:create, :update, :destroy], Admin
      cannot :create, Reservation
    elsif user.role == 'user'
      can :read, [Book, Author, Copy]
      can :read, User, id: user.id
      can :read, Borrow, user_id: user.id
      can :create, Reservation
      can :manage, Reservation, user_id: user.id
    else # guest
      can :read, [Book, Author, Copy]
      can :create, User
    end
  end
end

app/models/admin.rb
# Admins used with Authlogic.
# Specifies encryption protocol.
# role used for authorizating access by CanCanCan.
class Admin < ApplicationRecord
  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end

  def role
    if !current_user.nil?
      'user'
    elsif !current_admin.nil?
      if current_admin.login == 'admin'
        'sysadmin'
      else
        'admin'
      end
    else
      'guest'
    end
  end
end

app/models/admin_session.rb
# Authlogic module for storing sessions.
class AdminSession < Authlogic::Session::Base
end

app/models/application_record.rb
# current_% methods used for authentification by Authlogic
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def current_admin_session
    return @current_admin_session if defined?(@current_admin_session)
    @current_admin_session = AdminSession.find
  end

  def current_admin
    return @current_admin if defined?(@current_admin)
    @current_admin = current_admin_session && current_admin_session.admin
  end
end

app/models/author.rb
# Author model
class Author < ApplicationRecord
  has_and_belongs_to_many :books
  validates :name, presence: true
  validates :goodreads_id, presence: true
end

app/models/authors_book.rb
# AuthorsBook model
class AuthorsBook < ApplicationRecord
  validates :author_id, presence: true
  validates :book_id, presence: true
end

app/models/book.rb
# Book model
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  has_many :copies, dependent: :destroy
  has_many :reservations, dependent: :destroy
  validates :title, presence: true
  validates :isbn, presence: true
  validates :goodreads_id, presence: true
end

app/models/borrow.rb
# Borrow model
class Borrow < ApplicationRecord
  belongs_to :user
  belongs_to :copy
  validates :user_id, presence: true
  validates :copy_id, presence: true
  validates :due_date, presence: true
end

app/models/copy.rb
# Copy model
class Copy < ApplicationRecord
  belongs_to :book
  has_one :borrow, dependent: :destroy
  validates :status, presence: true
  validates :book_id, presence: true
end

app/models/reservation.rb
# Reservation model
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :user_id, presence: true
  validates :book_id, presence: true
end

app/models/user.rb
# Users used with Authlogic.
# Specifies encryption protocol.
# role used for authorizating access by CanCanCan.
class User < ApplicationRecord
  has_many :reservations
  has_many :borrows

  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end

  def role
    if !current_user.nil?
      'user'
    elsif !current_admin.nil?
      if current_admin.login == 'admin'
        'sysadmin'
      else
        'admin'
      end
    else
      'guest'
    end
  end
end

app/models/user_session.rb
# Authlogic module for storing sessions.
class UserSession < Authlogic::Session::Base
end

app/controllers/authors_controller.rb
# Author controller
class AuthorsController < ApplicationController
  load_and_authorize_resource

  def index
    @authors = Author.order(:name)
  end

  def show
    @author = Author.find(params[:id])
    @books = @author.books.order(:title)
    client = Goodreads.new(Goodreads.configuration)
    @grauthor = client.author(@author.goodreads_id)
  end

  def new
    @author = Author.new
    @grauthor = params[:grauthor]
  end

  def edit
    @author = Author.find(params[:id])
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      flash[:success] = 'Author added!'
      redirect_to @author
    else
      render 'new'
    end
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      flash[:success] = 'Author updated!'
      redirect_to @author
    else
      render 'edit'
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    flash[:success] = 'Author deleted!'
    redirect_to authors_path
  end

  def handle_search
    begin
      client = Goodreads.new(Goodreads.configuration)
      @grauthor = client.author_by_name(params[:name])
    rescue Goodreads::NotFound
      @grauthor = { name: 'no author found' }
    end
    flash[:success] = @grauthor[:name]
    redirect_to new_author_path(grauthor: @grauthor)
  end

  private

  def author_params
    params.require(:author).permit(:name, :goodreads_id)
  end
end

app/helpers/admins_helper.rb
# Empty helper so far.
module AdminsHelper
end

app/helpers/application_helper.rb
# Empty helper so far.
module ApplicationHelper
end

app/helpers/author_books_helper.rb
# Empty helper so far.
module AuthorBooksHelper
end

app/helpers/authors_helper.rb
# Empty helper so far.
module AuthorsHelper
end

app/helpers/books_helper.rb
# Empty helper so far.
module BooksHelper
end

app/helpers/borrows_helper.rb
# Empty helper so far.
module BorrowsHelper
end

app/helpers/copies_helper.rb
# Empty helper so far.
module CopiesHelper
end

app/helpers/reservations_helper.rb
# Empty helper so far.
module ReservationsHelper
end

app/helpers/users_helper.rb
# Empty helper so far.
module UsersHelper
end

app/helpers/welcome_helper.rb
# Empty helper so far.
module WelcomeHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
  <% if @author.errors.any? %>
    <div class="panel panel-warning errors">
      <div class="panel-heading">
        <h2>
          <i class="glyphicon glyphicon-exclamation-sign"></i> <%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:
        </h2>
      </div>
      <ul class="panel-body">
        <% @author.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :goodreads_id %><br>
    <%= f.text_field :goodreads_id, class: 'form-control' %>
  </div>
 
  <%= f.submit %>

 
<% end %>

app/views/authors/edit.html.erb
<div class="page-header">
  <h1>Editing author</h1>
</div>
 
<%= render 'form' %>
 
<br>
<%= link_to 'Back to Authors', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<% if can? :create, Author %> 
   <%#= link_to 'Add author', new_author_path %>
   <%= link_to 'Add author', search_authors_path %>
   <br><br>
<% end %>  
 
<table class="table">
  <tr>
    <th>Name</th>
    <th>Goodreads ID</th>
    <th>Books</th>
  </tr>
 
  <% @authors.each do |author| %>
    <tr>
      <td><%= author.name %></td>
      <td><%= author.goodreads_id %></td>
      <td><%= author.books.count %></td>
      <td><%= link_to 'Show', author_path(author) %></td>
      <% if can? :manage, Author %> 
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Delete', author_path(author),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      <% end %>  
    </tr>
  <% end %>
</table>

<%= link_to 'Home', root_path %>

app/views/authors/new.html.erb
<div class="page-header">
  <h1>New Author</h1>
</div>

<%= form_for @author do |f| %>
  <% if @author.errors.any? %>
    <div class="panel panel-warning errors">
      <div class="panel-heading">
        <h2>
          <i class="glyphicon glyphicon-exclamation-sign"></i> <%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:
        </h2>
      </div>
      <ul class="panel-body">
        <% @author.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= f.label :name, @grauthor[:name] %><br>
    <%= f.hidden_field :name, value: @grauthor[:name] %>
  </div>
  
  <div class="form-group">
    <%= f.hidden_field :goodreads_id, value: @grauthor[:id] %>
  </div>
  
  <% if @grauthor[:name] != 'no author found' %>
    <%= f.submit %>
  <% end %>
  
<% end %>

<br>
Not the author you have been searching for?
<%= link_to 'Specify authors name', search_authors_path %>

<br><br>
<%= link_to 'Back to authors', authors_path %>

app/views/authors/search.html.erb
<div class="page-header">
  <h1>Search for author</h1>
</div>

<%= form_tag handle_search_authors_path, method: "get" do %>

  <div class="form-group">
    <%= label_tag :name, 'Author name:' %><br>
    <%= text_field_tag :name %>
  </div>
 
  <%= submit_tag 'Search', name: nil %>
<% end %>

<br><br>
<%= link_to 'Back to authors', authors_path %>

app/views/authors/show.html.erb
<h2>
  <%= @author.name %>
</h2>
<p>
  <strong>Godreads ID:</strong>
  <%= @author.goodreads_id %>
</p>
<p>
  <strong>Born:</strong>
  <%= @grauthor.born_at %>, 
  <strong>Died:</strong>
  <%= @grauthor.died_at %>
</p>
 
<p>
  <u>About:</u>
  <br>
  <%= raw(@grauthor.about) %>
  <p>
    Info gathered from:
    <%= link_to @grauthor.link, @grauthor.link %>
  </p>
</p>

<h2>Books</h2>
<% if can? :manage, Author %> 
  <%= link_to 'Add Book', new_authors_book_path(:author => @author) %>
  <br><br>
<% end %>
<% if !@books.blank? %>
  <ul class="list-group">
  <% @books.each do |book| %>
    <li class="list-group-item"><%= link_to book.title, book_path(book) %></li>
  <% end %>
  </ul>
<% else %>
  no books
  <br>
<% end %>



<br>
<% if can? :manage, Author %> 
  <%= link_to 'Edit', edit_author_path(@author) %> |
<% end %>
<%= link_to 'Back to authors', authors_path %>