config/routes.rb
Rails.application.routes.draw do
  resources :authors do
    collection do
      get 'search'
      get 'handle_search'
    end
  end
  resources :books do
    resources :copies
    resources :reservations
    collection do
      get 'search'
      get 'handle_search'
    end
  end

  resources :authors_books
  resources :borrows

  resources :users
  resources :user_sessions, only: [:create, :destroy]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resources :admins
  resources :admin_sessions, only: [:create, :destroy]
  delete '/admin_sign_out', to: 'admin_sessions#destroy', as: :admin_sign_out
  get '/admin_sign_in', to: 'admin_sessions#new', as: :admin_sign_in

  root 'welcome#index'
end

app/models/ability.rb
# Used by CanCanCan to initialize user rights.
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role == 'sysadmin'
      can :manage, :all
      cannot :create, Reservation
    elsif user.role == 'admin'
      can :manage, :all
      cannot [:create, :update, :destroy], Admin
      cannot :create, Reservation
    elsif user.role == 'user'
      can :read, [Book, Author, Copy]
      can :read, User, id: user.id
      can :read, Borrow, user_id: user.id
      can :create, Reservation
      can :manage, Reservation, user_id: user.id
    else # guest
      can :read, [Book, Author, Copy]
      can :create, User
    end
  end
end

app/models/admin.rb
# Admins used with Authlogic.
# Specifies encryption protocol.
# role used for authorizating access by CanCanCan.
class Admin < ApplicationRecord
  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end

  def role
    if !current_user.nil?
      'user'
    elsif !current_admin.nil?
      if current_admin.login == 'admin'
        'sysadmin'
      else
        'admin'
      end
    else
      'guest'
    end
  end
end

app/models/admin_session.rb
# Authlogic module for storing sessions.
class AdminSession < Authlogic::Session::Base
end

app/models/application_record.rb
# current_% methods used for authentification by Authlogic
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def current_admin_session
    return @current_admin_session if defined?(@current_admin_session)
    @current_admin_session = AdminSession.find
  end

  def current_admin
    return @current_admin if defined?(@current_admin)
    @current_admin = current_admin_session && current_admin_session.admin
  end
end

app/models/author.rb
# Author model
class Author < ApplicationRecord
  has_and_belongs_to_many :books
  validates :name, presence: true
  validates :goodreads_id, presence: true
end

app/models/authors_book.rb
# AuthorsBook model
class AuthorsBook < ApplicationRecord
  validates :author_id, presence: true
  validates :book_id, presence: true
end

app/models/book.rb
# Book model
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  has_many :copies, dependent: :destroy
  has_many :reservations, dependent: :destroy
  validates :title, presence: true
  validates :isbn, presence: true
  validates :goodreads_id, presence: true
end

app/models/borrow.rb
# Borrow model
class Borrow < ApplicationRecord
  belongs_to :user
  belongs_to :copy
  validates :user_id, presence: true
  validates :copy_id, presence: true
  validates :due_date, presence: true
end

app/models/copy.rb
# Copy model
class Copy < ApplicationRecord
  belongs_to :book
  has_one :borrow, dependent: :destroy
  validates :status, presence: true
  validates :book_id, presence: true
end

app/models/reservation.rb
# Reservation model
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :user_id, presence: true
  validates :book_id, presence: true
end

app/models/user.rb
# Users used with Authlogic.
# Specifies encryption protocol.
# role used for authorizating access by CanCanCan.
class User < ApplicationRecord
  has_many :reservations
  has_many :borrows

  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end

  def role
    if !current_user.nil?
      'user'
    elsif !current_admin.nil?
      if current_admin.login == 'admin'
        'sysadmin'
      else
        'admin'
      end
    else
      'guest'
    end
  end
end

app/models/user_session.rb
# Authlogic module for storing sessions.
class UserSession < Authlogic::Session::Base
end

app/controllers/users_controller.rb
# User controller
class UsersController < ApplicationController
  load_and_authorize_resource except: :create

  def index
    @users = User.accessible_by(current_ability, :read).order(:login)
  end

  def show
    @user = User.find(params[:id])
    @reservations = Reservation.where(user_id: @user.id)
    @borrows = Borrow.where(user_id: @user.id)
    @borrow = Borrow.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      flash[:success] = 'Account registered!'
      redirect_to root_path
    else
      render :new
    end
    # authorize! :create, @user
  end

  private

  def users_params
    params.require(:user).permit(:login, :password, :password_confirmation)
  end
end

app/helpers/admins_helper.rb
# Empty helper so far.
module AdminsHelper
end

app/helpers/application_helper.rb
# Empty helper so far.
module ApplicationHelper
end

app/helpers/author_books_helper.rb
# Empty helper so far.
module AuthorBooksHelper
end

app/helpers/authors_helper.rb
# Empty helper so far.
module AuthorsHelper
end

app/helpers/books_helper.rb
# Empty helper so far.
module BooksHelper
end

app/helpers/borrows_helper.rb
# Empty helper so far.
module BorrowsHelper
end

app/helpers/copies_helper.rb
# Empty helper so far.
module CopiesHelper
end

app/helpers/reservations_helper.rb
# Empty helper so far.
module ReservationsHelper
end

app/helpers/users_helper.rb
# Empty helper so far.
module UsersHelper
end

app/helpers/welcome_helper.rb
# Empty helper so far.
module WelcomeHelper
end

app/views/users/index.html.erb
<h1>Listing users</h1>
 
<table class="table">
  <tr>
    <th>ID</th>
    <th>Login</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.login %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
    </tr>
  <% end %>
</table> 

<%= link_to 'Home', root_path %>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Register</h1>
</div>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="panel panel-warning errors">
      <div class="panel-heading">
        <h2>
          <i class="glyphicon glyphicon-exclamation-sign"></i> <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
        </h2>
      </div>
      <ul class="panel-body">
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :login %>
    <%= f.text_field :login, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>
<% end %>
<br>
<%= link_to 'Home', root_path %>

app/views/users/show.html.erb
<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<h2>Issued books:</h2>

<% if !@borrows.blank? %>
  <%= render partial: "borrows/borrow", collection: @borrows, as: :borrow %>
<% else %>
  <p>
    No issued books.
  </p>
<% end%>


<h2>Reservations:</h2>

<% if !@reservations.blank? %>
  <%= render partial: "reservations/show", collection: @reservations, as: :reservation %>
<% else %>
  <p>
    No reservations.
  </p>
<% end%>

<% if can? :create, Borrow %>
  <h2>Issue a book:</h2>
    <%= form_for @borrow do |f| %>
      <p>
        <%= f.label :copy_id %><br>
        <%= f.collection_select(:copy_id, Copy.where(:status => 0), :id, :id, prompt: true ) %>
      </p>
      
      <p>
        <%= f.hidden_field :user_id, :value => @user.id %>
        <%= f.hidden_field :due_date, :value => Date.today + 30 %>
      </p>
     
      <p>
        <%= f.submit 'Issue book', class: 'btn btn-primary btn-lg' %>
      </p>
    <% end %>
<% end %>
<br>
<% if can? :manage, User%>
  <%= link_to 'Back', users_path %>
<% else %>
  <%= link_to 'Home', root_path %>
<% end %>