config/routes.rb
Rails.application.routes.draw do
  resources :authors do
    collection do
      get 'search'
      get 'handle_search'
    end
  end
  resources :books do
    resources :copies
    resources :reservations
    collection do
      get 'search'
      get 'handle_search'
    end
  end

  resources :authors_books
  resources :borrows

  resources :users
  resources :user_sessions, only: [:create, :destroy]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  resources :admins
  resources :admin_sessions, only: [:create, :destroy]
  delete '/admin_sign_out', to: 'admin_sessions#destroy', as: :admin_sign_out
  get '/admin_sign_in', to: 'admin_sessions#new', as: :admin_sign_in

  root 'welcome#index'
end

app/models/ability.rb
# Used by CanCanCan to initialize user rights.
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role == 'sysadmin'
      can :manage, :all
      cannot :create, Reservation
    elsif user.role == 'admin'
      can :manage, :all
      cannot [:create, :update, :destroy], Admin
      cannot :create, Reservation
    elsif user.role == 'user'
      can :read, [Book, Author, Copy]
      can :read, User, id: user.id
      can :read, Borrow, user_id: user.id
      can :create, Reservation
      can :manage, Reservation, user_id: user.id
    else # guest
      can :read, [Book, Author, Copy]
      can :create, User
    end
  end
end

app/models/admin.rb
# Admins used with Authlogic.
# Specifies encryption protocol.
# role used for authorizating access by CanCanCan.
class Admin < ApplicationRecord
  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end

  def role
    if !current_user.nil?
      'user'
    elsif !current_admin.nil?
      if current_admin.login == 'admin'
        'sysadmin'
      else
        'admin'
      end
    else
      'guest'
    end
  end
end

app/models/admin_session.rb
# Authlogic module for storing sessions.
class AdminSession < Authlogic::Session::Base
end

app/models/application_record.rb
# current_% methods used for authentification by Authlogic
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def current_admin_session
    return @current_admin_session if defined?(@current_admin_session)
    @current_admin_session = AdminSession.find
  end

  def current_admin
    return @current_admin if defined?(@current_admin)
    @current_admin = current_admin_session && current_admin_session.admin
  end
end

app/models/author.rb
# Author model
class Author < ApplicationRecord
  has_and_belongs_to_many :books
  validates :name, presence: true
  validates :goodreads_id, presence: true
end

app/models/authors_book.rb
# AuthorsBook model
class AuthorsBook < ApplicationRecord
  validates :author_id, presence: true
  validates :book_id, presence: true
end

app/models/book.rb
# Book model
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  has_many :copies, dependent: :destroy
  has_many :reservations, dependent: :destroy
  validates :title, presence: true
  validates :isbn, presence: true
  validates :goodreads_id, presence: true
end

app/models/borrow.rb
# Borrow model
class Borrow < ApplicationRecord
  belongs_to :user
  belongs_to :copy
  validates :user_id, presence: true
  validates :copy_id, presence: true
  validates :due_date, presence: true
end

app/models/copy.rb
# Copy model
class Copy < ApplicationRecord
  belongs_to :book
  has_one :borrow, dependent: :destroy
  validates :status, presence: true
  validates :book_id, presence: true
end

app/models/reservation.rb
# Reservation model
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :user_id, presence: true
  validates :book_id, presence: true
end

app/models/user.rb
# Users used with Authlogic.
# Specifies encryption protocol.
# role used for authorizating access by CanCanCan.
class User < ApplicationRecord
  has_many :reservations
  has_many :borrows

  acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
  end

  def role
    if !current_user.nil?
      'user'
    elsif !current_admin.nil?
      if current_admin.login == 'admin'
        'sysadmin'
      else
        'admin'
      end
    else
      'guest'
    end
  end
end

app/models/user_session.rb
# Authlogic module for storing sessions.
class UserSession < Authlogic::Session::Base
end

app/controllers/borrows_controller.rb
# Borrow controller
class BorrowsController < ApplicationController
  load_and_authorize_resource

  def index
    @borrows = Borrow.all
  end

  def show
    @borrow = Borrow.find(params[:id])
    @user = User.find(@borrow.user_id)
    @book = Book.find(Copy.find(@borrow.copy_id).book_id)
  end

  def new
    @borrow = Borrow.new
  end

  def create
    @borrow = Borrow.new(borrow_params)
    if @borrow.save
      flash[:success] = 'Book issued!'
      Copy.find(@borrow.copy_id).update(status: 1)
      redirect_to @borrow
    else
      render :new
    end
  end

  def destroy
    @borrow = Borrow.find(params[:id])
    Copy.find(@borrow.copy_id).update(status: 0)
    flash[:success] = 'Book returned!'
    @borrow.destroy

    redirect_to borrows_path
  end

  private

  def borrow_params
    params.require(:borrow).permit(:user_id, :copy_id, :due_date)
  end
end

app/helpers/admins_helper.rb
# Empty helper so far.
module AdminsHelper
end

app/helpers/application_helper.rb
# Empty helper so far.
module ApplicationHelper
end

app/helpers/author_books_helper.rb
# Empty helper so far.
module AuthorBooksHelper
end

app/helpers/authors_helper.rb
# Empty helper so far.
module AuthorsHelper
end

app/helpers/books_helper.rb
# Empty helper so far.
module BooksHelper
end

app/helpers/borrows_helper.rb
# Empty helper so far.
module BorrowsHelper
end

app/helpers/copies_helper.rb
# Empty helper so far.
module CopiesHelper
end

app/helpers/reservations_helper.rb
# Empty helper so far.
module ReservationsHelper
end

app/helpers/users_helper.rb
# Empty helper so far.
module UsersHelper
end

app/helpers/welcome_helper.rb
# Empty helper so far.
module WelcomeHelper
end

app/views/borrows/_borrow.html.erb
<p>
  <strong>Book:</strong>
  <%= Book.find(Copy.find(borrow.copy_id).book_id).title %>
  
  <%= link_to 'Show', borrow_path(borrow)%>
  <% if can? :manage, Borrow %> 
    | <%= link_to 'Return Book', borrow_path(borrow),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
  <% end %>
</p>

app/views/borrows/index.html.erb
<h1>Issued books</h1>

<% if can? :create, Borrow %>  
  <%= link_to 'Issue a book', new_borrow_path %>
  <br><br>
<% end %> 

<table class="table">
  <tr>
    <th>Copy ID</th>
    <th>Book</th>
    <th>User</th>
    <th>Due Date</th>
  </tr>
 
  <% @borrows.each do |borrow| %>
    <tr>
      <td><%= borrow.copy_id %></td>
      <td><%= Book.find(Copy.find(borrow.copy_id).book_id).title %></td>
      <td><%= User.find(borrow.user_id).login %></td>
      <td><%= borrow.due_date %></td>
      <td><%= link_to 'Show', borrow_path(borrow) %></td>
      <% if can? :manage, Borrow %> 
        <td><%= link_to 'Return Book', borrow_path(borrow),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<%= link_to 'Home', root_path %>

app/views/borrows/new.html.erb
<div class="page-header">
  <h1>Issue book</h1>
</div>

<%= form_for @borrow do |f| %>
  <% if @borrow.errors.any? %>
    <div class="panel panel-warning errors">
      <div class="panel-heading">
        <h2>
          <i class="glyphicon glyphicon-exclamation-sign"></i> <%= pluralize(@borrow.errors.count, "error") %> prohibited issuing from finishing:
        </h2>
      </div>
      <ul class="panel-body">
        <% @borrow.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <%= f.label :copy_id  %><br>
    <%= f.collection_select(:copy_id, Copy.where(:status => 0), :id, :id, prompt: true ) %>
  </div>
  
  <div class="form-group">
    <%= f.label :user_id %><br>
    <%= f.collection_select(:user_id, User.order(:login), :id, :login, prompt: true ) %>
  </div>
 
  <%= f.hidden_field :due_date, :value => Date.today + 30 %>
 
  <%= f.submit 'Issue', class: 'btn btn-primary btn-lg' %>
 
<% end %>

@params

<br>
<%= link_to 'Back to issued', borrows_path %>

app/views/borrows/show.html.erb
<h2>Issued book</h2>

<strong>Book:</strong>
<p>
  <%= link_to @book.title, book_path(@book) %>,
  <strong>Copy:</strong>
  <%= @borrow.copy_id %>
</p>
<strong>Issued to:</strong>
<p>
  <%= link_to @user.login, user_path(@user) %>,
  <strong>Id:</strong>
  <%= @borrow.user_id %>
</p>
<strong>Due Date:</strong>
<p>
  <%= @borrow.due_date %>
</p>

<% if can? :manage, Borrow %>
  <%= link_to 'To Issued Books', borrows_path %>
<% else %>
  <%= link_to 'Home', root_path %>
<% end %>